spring:
  application:
    name: my-wallet
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: Zufu@123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2
jwt:
  secret: javainuse
  get:
    token:
      uri: /authenticate

